from numpy import *
first=array([[10,20,30],[40,50,60]])
second=array([[70,80,90],[100,110,120]])
print(first)
print("\n")
print(second)
print("hstack")
print(hstack((first,second)))
print("\n")
print("vstack")
print(vstack((first,second)))
print("\n")
print("column stack")
print(column_stack((first,second)))